### ISSUE TITLE
menu ancestor indicator is a longie

### ISSUE THREAD

**Issue by johnpennypacker** [uriweb/uri-modern#119]
## Issue Type

[x] Bug  
[] New Feature  
[] Enhancement  
    
## Description

The ancestor indicator is the fullwidth of the list item, but the current page indicator is the width of the text.

![image](https://user-images.githubusercontent.com/34277245/42165721-e9cd968c-7dd6-11e8-823a-f358f9f6ba05.png)

## Steps to Reproduce

1. Visit a page that is child of a page in the menu.

**Expected behavior:** [What you expect to happen]

Underline is the same length as the current page indicator

**Comment by bjcfuller** [comment]
This largely applies to the [component library](https://github.com/uriweb/uri-component-library), but it should be updated here as well.

**Comment by bjcfuller** [comment]
I was mistaken, this is all to do with the theme styles.
