### ISSUE TITLE
add indicator for menu ancestor

### ISSUE THREAD

**Issue by johnpennypacker** [uriweb/uri-modern#65]
class .current-page-ancestor would be lovely if it were styled in a distinct way

e.g. https://harrington.uri.edu/academics/library-and-information-studies/mlis-curriculum/lsc-course-schedules/

**Comment by bjcfuller** [comment]
This issue relates to the [component library](https://github.com/uriweb/uri-component-library).

**Comment by bjcfuller** [comment]
Looks like this issue relates to the theme as well as the component library, so reopening.
